apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-data
          mountPath: /data
      command:
        - "/bin/bash"
        - "-c"
        - |
            # รัน nginx และทำงานเพิ่มเติม
            nginx & # รัน nginx เบื้องหลัง

            # กำหนดชื่อ pod
            POD_NAME=$(hostname)
            
            # ตรวจสอบและสร้างไฟล์
            mkdir -p /data1
            while true; do
              # หาชื่อไฟล์ล่าสุด
              last_file=$(ls /data/nginx-${POD_NAME}-* 2>/dev/null | sort -V | tail -n 1)
              if [ -n "$last_file" ]; then
                # หากมีไฟล์อยู่แล้ว สร้างไฟล์ถัดไป
                next_num=$(echo $last_file | sed -E 's/.*-(\d+)$/\1/' | awk '{print $1+1}')
              else
                # หากยังไม่มีไฟล์ สร้างไฟล์แรก
                next_num=1
              fi
              echo ${next_num}
              # สร้างไฟล์ใหม่
              echo "nginx-${POD_NAME}-${next_num} $(date)" > /data/nginx-${POD_NAME}-${next_num}

              # คัดลอกไฟล์จาก /data ไปยัง /data1
              cp /data/nginx-${POD_NAME}-${next_num} /data1/
              
              sleep 30
            done
  volumes:
    - name: nginx-data
      persistentVolumeClaim:
        claimName: nginx-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
  namespace: nginx
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
